-- ============================================
-- SETUP COMPLETO DATABASE + IMPORT DOMANDE
-- Esegui questo script nel SQL Editor di Supabase
-- ============================================

-- 1. Crea la tabella questions
CREATE TABLE IF NOT EXISTS questions (
  id SERIAL PRIMARY KEY,
  question TEXT NOT NULL,
  answers TEXT[] NOT NULL,
  correct_answer TEXT NOT NULL,
  category TEXT,
  explanation TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. Abilita Row Level Security
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

-- 3. Policy per lettura pubblica
DROP POLICY IF EXISTS "Lettura pubblica delle domande" ON questions;
CREATE POLICY "Lettura pubblica delle domande"
ON questions FOR SELECT
TO public
USING (true);

-- 4. Indici per performance
CREATE INDEX IF NOT EXISTS idx_questions_category ON questions(category);
CREATE INDEX IF NOT EXISTS idx_questions_created_at ON questions(created_at DESC);

-- ============================================
-- DOMANDE - TOPONOMASTICA PALERMO (40)
-- ============================================

INSERT INTO questions (question, answers, correct_answer, category, explanation) VALUES
('DOVE HA SEDE L''ASSESSORATO REGIONALE DELLE INFRASTRUTTURE DEI TRASPORTI E DELLA MOBILITA'' A PALERMO', ARRAY['VIA MAQUEDA', 'VIA LEONARDO DA VINCI', 'VIA LIBERTA'''], 'VIA LEONARDO DA VINCI', 'Toponomastica Palermo', NULL),
('DOVE HA SEDE LA POLIZIA MUNICIPALE DEL COMUNE DI PALERMO ?', ARRAY['VIA UGO LA MALFA, 72', 'VIA GARIBALDI', 'VIA SICILIA'], 'VIA UGO LA MALFA, 72', 'Toponomastica Palermo', NULL),
('DOVE SI PUO'' GUSTARE GASTRONOMIA PALERMITANA', ARRAY['BAR DEL CORSO', 'FOCACCERIA SAN FRANCESCO', 'PIZZERIA TRINACRIA'], 'FOCACCERIA SAN FRANCESCO', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA IL TEATRO MASSIMO DI PALERMO ?', ARRAY['VIA LIBERTA''', 'PIAZZA VERDI', 'VIA ROMA'], 'PIAZZA VERDI', 'Toponomastica Palermo', 'Il Teatro Massimo, uno dei più grandi teatri d''opera d''Europa, si trova in Piazza Verdi'),
('LA CAPPELLA PALATINA SI TROVA A:', ARRAY['PALAZZO MIRTO', 'PALAZZO BUTERA', 'PALAZZO REALE O DEI NORMANNI'], 'PALAZZO REALE O DEI NORMANNI', 'Toponomastica Palermo', NULL),
('IN QUALE VIALE SI TROVA LO STADIO COMUNALE DI CALCIO DI PALERMO ?', ARRAY['VIALE DELLE PROVINCE', 'VIALE EUROPA', 'VIALE DEL FANTE'], 'VIALE DEL FANTE', 'Toponomastica Palermo', NULL),
('IN QUALE VIA A PALERMO SI TROVA L''ISTITUTO MEDITERRANEO TRAPIANTI (ISMETT)', ARRAY['VIA E. BASILE', 'CORSO TUKORY', 'VIA E. TRICOMI'], 'VIA E. TRICOMI', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA L''OSPEDALE CERVELLO DI PALERMO ?', ARRAY['VIALE STRASBURGO', 'PIAZZA CRISTOFORO COLOMBO', 'VIA TRABUCCO'], 'VIA TRABUCCO', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA S. GIOVANNI DEGLI EREMITI:', ARRAY['PALERMO', 'CEFALU''', 'MONREALE'], 'PALERMO', 'Toponomastica Palermo', NULL),
('DOV''E'' SITUATA LA PREFETTURA DI PALERMO', ARRAY['PIAZZA EUROPA', 'VIA CAVOUR', 'PIAZZA GIULIO CESARE'], 'VIA CAVOUR', 'Toponomastica Palermo', NULL),
('DOV''E'' UBICATA LA CURIA ARCIVESCOVILE DELLA DIOCESI DI PALERMO', ARRAY['VIA M. BONELLO', 'VIA PAOLO BORSELLINO', 'VIA A. DE GASPERI'], 'VIA M. BONELLO', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA MONDELLO:', ARRAY['A CEFALU''', 'A PALERMO', 'A TERRASINI'], 'A PALERMO', 'Toponomastica Palermo', NULL),
('IL TRIBUNALE DI PALERMO SI TROVA IN:', ARRAY['PIAZZA VITTORIO EMANUELE ORLANDO', 'PIAZZA DELLA LIBERTA', 'PIAZZA TREDICI VITTIME'], 'PIAZZA VITTORIO EMANUELE ORLANDO', 'Toponomastica Palermo', NULL),
('IN QUALE CITTA'' SI TROVA IL MUSEO ETNOGRAFICO PITRE'':', ARRAY['AGRIGENTO', 'PALERMO', 'RAGUSA'], 'PALERMO', 'Toponomastica Palermo', NULL),
('IN QUALE CITTA'' SI TROVA IL PARCO DELLA FAVORITA', ARRAY['TRAPANI', 'CATANIA', 'PALERMO'], 'PALERMO', 'Toponomastica Palermo', NULL),
('IN QUALE PIAZZA DI PALERMO SI TROVA L''ALBERO SECOLARE', ARRAY['PIAZZA MARINA', 'PIAZZA GIULIO CESARE', 'PIAZZA SAN DOMENICO'], 'PIAZZA MARINA', 'Toponomastica Palermo', NULL),
('IN QUALE VIA HA SEDE LA GUARDIA COSTIERA DI PALERMO ?', ARRAY['VIA NOTARBARTOLO', 'VIALE CRISTOFORO COLOMBO', 'VIA F. CRISPI'], 'VIA F. CRISPI', 'Toponomastica Palermo', NULL),
('IN QUALE VIA SI TROVA L''I.N.P.S. DI PALERMO SEDE ?', ARRAY['VIA TRIESTE', 'VIA LAURANA', 'VIA DIAZ'], 'VIA LAURANA', 'Toponomastica Palermo', NULL),
('IN QUALE ZONA E'' UBICATO L''HOTEL DELLE PALME A PALERMO?', ARRAY['VIA CATANIA', 'VIA NAPOLI', 'VIA ROMA'], 'VIA ROMA', 'Toponomastica Palermo', NULL),
('I GIARDINI DELLA CONCA D''ORO SI TROVANO A :', ARRAY['TRAPANI', 'CALTANISSETTA', 'PALERMO'], 'PALERMO', 'Toponomastica Palermo', NULL),
('L''ASSEMBLEA DEL PARLAMENTO SICILIANO SI TROVA:', ARRAY['NEL PALAZZO REALE O DEI NORMANNI', 'PALAZZO PRETORIO O DELLE AQUILE', 'PALAZZO COMITINI'], 'NEL PALAZZO REALE O DEI NORMANNI', 'Toponomastica Palermo', NULL),
('IL PRESIDENTE DELLA REGIONE SICILIANA SI TROVA:', ARRAY['PALAZZO D''ORLEANS', 'PALAZZO STERI O CHIARAMONTE', 'PALAZZO BUTERA'], 'PALAZZO D''ORLEANS', 'Toponomastica Palermo', NULL),
('LA SEDE DEI VIGILI DEL FUOCO DI PALERMO SI TROVA IN:', ARRAY['VIA IV NOVEMBRE', 'VIA ALESSANDRO SCARLATTI', 'VIA ROMA'], 'VIA ALESSANDRO SCARLATTI', 'Toponomastica Palermo', NULL),
('L''AEROPORTO DI PALERMO (FALCONEBORSELLINO GIA'' PUNTA RAISI) SI TROVA NEL TERRITORIO DI:', ARRAY['PALERMO', 'CINISI', 'TERRASINI'], 'CINISI', 'Toponomastica Palermo', NULL),
('LE MURA DELLE CATTIVE, SI TROVANO NELLA CITTA'' DI:', ARRAY['AGRIGENTO', 'CATANIA', 'PALERMO'], 'PALERMO', 'Toponomastica Palermo', NULL),
('L''ORTO BOTANICO A PALERMO SI TROVA:', ARRAY['IN VIA ROMA', 'IN VIA LINCOLN', 'IN VIA LIBERTA'''], 'IN VIA LINCOLN', 'Toponomastica Palermo', NULL),
('L''UNIVERSITA'' DEGLI STUDI DI PALERMO HA SEDE IN:', ARRAY['VIALE DELLE OLIMPIADI', 'VIALE DELLE SCIENZE', 'VIALE REGIONE SICILIANA'], 'VIALE DELLE SCIENZE', 'Toponomastica Palermo', NULL),
('QUALE DI QUESTE FIERE SI SVOLGEVA A PALERMO:', ARRAY['FIERA DEL MEDITERRANEO', 'FIERA FRANCA O CAMPIONARIA', 'FIERA DEL LEVANTE'], 'FIERA DEL MEDITERRANEO', 'Toponomastica Palermo', NULL),
('QUALE DI QUESTI HOTELS DI PALERMO E'' A CINQUE STELLE', ARRAY['ASTORIA PALACE HOTEL', 'HOTEL EUROPA', 'VILLA IGIEA HILTON'], 'VILLA IGIEA HILTON', 'Toponomastica Palermo', NULL),
('QUALE DI QUESTI HOTELS DI PALERMO E'' A TRE STELLE', ARRAY['CENTRALE PALACE HOTEL', 'HOTEL EUROPA', 'GRAND HOTEL WAGNER'], 'HOTEL EUROPA', 'Toponomastica Palermo', NULL),
('QUALE DI QUESTI HOTELS DI PALERMO E'' A QUATTRO STELLE', ARRAY['SAN PAOLO PALACE', 'CASENA DEI COLLI', 'HOTEL PONTE'], 'SAN PAOLO PALACE', 'Toponomastica Palermo', NULL),
('QUALE DI QUESTI PALAZZI STORICI DI PALERMO SI TROVA IN PIAZZA DEL PARLAMENTO', ARRAY['PALAZZO DEI NORMANNI', 'PALAZZO PRETORIO', 'PALAZZO MIRTO'], 'PALAZZO DEI NORMANNI', 'Toponomastica Palermo', NULL),
('QUALI DI QUESTI IMPORTANTI TEATRI SI TROVA A PALERMO:', ARRAY['IL POLITEAMA GARIBALDI', 'IL TEATRO ALLA SCALA', 'IL SAN CARLO'], 'IL POLITEAMA GARIBALDI', 'Toponomastica Palermo', NULL),
('QUALI DI QUESTI PITTORESCHI MERCATI SI TROVA A PALERMO:', ARRAY['IL MERCATO DELLA " VUCCIRIA"', 'IL MERCATO DI "POSILLIPO"', 'IL MERCATO DI " ARABAL"'], 'IL MERCATO DELLA " VUCCIRIA"', 'Toponomastica Palermo', NULL),
('IL MERCATO STORICO DI " BALLARO'' " SI TROVA A:', ARRAY['TRAPANI', 'AGRIGENTO', 'PALERMO'], 'PALERMO', 'Toponomastica Palermo', NULL),
('VILLA NISCEMI A PALERMO E'' SEDE DI:', ARRAY['E'' LA SEDE DI RAPPRESENTANZA DEL COMUNE DI PALERMO', 'E'' LA SEDE DI RAPPRESENTANZA DELLA PROVINCIA DI PALERMO', 'E'' LA SEDE DI RAPPRESENTANZA DELLA REGIONE SICILIA'], 'E'' LA SEDE DI RAPPRESENTANZA DEL COMUNE DI PALERMO', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA IL SANTUARIO DI SANTA ROSALIA:', ARRAY['MONTE CATALFANO', 'MONTE PELLEGRINO', 'MONTE CUCCO'], 'MONTE PELLEGRINO', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA LA STAZIONE MARITTIMA DI PALERMO', ARRAY['VIA GIULIO CESARE', 'VIA MESSINA MARINE', 'VIA CRISPI'], 'VIA CRISPI', 'Toponomastica Palermo', NULL),
('DOVE SI TROVA LA STAZIONE CENTRALE DI PALERMO:', ARRAY['VIA EMERICO AMARI', 'VIA ROMA', 'PIAZZA GIULIO CESARE'], 'PIAZZA GIULIO CESARE', 'Toponomastica Palermo', NULL),
('VILLA GIULIA A PALERMO SI TROVA:', ARRAY['IN VIA DANTE', 'IN VIA ABRAMO LINCOLN', 'CORSO RE RUGGERO'], 'IN VIA ABRAMO LINCOLN', 'Toponomastica Palermo', NULL);

-- Verifica inserimento
SELECT COUNT(*) as domande_inserite FROM questions WHERE category = 'Toponomastica Palermo';
